# Generated by Django 4.1.2 on 2022-10-18 09:14

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('cache_time', models.IntegerField(default=0)),
            ],
        ),
    ]
